### ISSUE TITLE
<code text>の文字/背景色をかえたい

### ISSUE THREAD

**Issue by kanehis** [kanehis/dokuwiki_template#1]
## 理由 ##
背景色がかわってやや読みにくいかも
　特にbox-shadowとborderが気になる
　　borderをとっぱらうとcodeの境界線がわからなくなる
　　　わかる必要ある？
字の文的な扱いで読みたい

修正案一例
```css
.code.text {
    background-color: initial;
    box-shadow: none;
    border: none;
}
```
